import { useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { ScrollArea } from '@/components/ui/scroll-area';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Loader2, TrendingUp, TrendingDown, ArrowUpDown, FolderOpen, FileText, DollarSign, CalendarDays } from 'lucide-react';
import { CurrencyInput } from '@/components/shared/CurrencyInput';
import { TransactionFormData, Transaction } from '@/hooks/useTransactions';

const transactionSchema = z.object({
  type: z.enum(['income', 'expense']),
  description: z.string().min(2, 'Descrição deve ter pelo menos 2 caracteres').max(200),
  amount: z.coerce.number().positive('Valor deve ser positivo'),
  date: z.string().optional(),
  category: z.string().optional(),
});

const EXPENSE_CATEGORIES = [
  'Insumos',
  'Embalagens',
  'Combustível',
  'Equipamentos',
  'Marketing',
  'Aluguel',
  'Outros',
];

const INCOME_CATEGORIES = [
  'Sinal',
  'Pagamento Final',
  'Venda Avulsa',
  'Outros',
];

interface TransactionFormDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSubmit: (data: TransactionFormData) => Promise<void>;
  isLoading: boolean;
  defaultType?: 'income' | 'expense';
  transaction?: Transaction | null;
}

export function TransactionFormDialog({
  open,
  onOpenChange,
  onSubmit,
  isLoading,
  defaultType = 'expense',
  transaction,
}: TransactionFormDialogProps) {
  const isEditing = !!transaction;
  
  // Parse category from description if editing
  const parseDescriptionAndCategory = (description: string | null) => {
    if (!description) return { category: '', desc: '' };
    const dashIndex = description.indexOf(' - ');
    if (dashIndex > 0) {
      const category = description.substring(0, dashIndex);
      const desc = description.substring(dashIndex + 3);
      const allCategories = [...EXPENSE_CATEGORIES, ...INCOME_CATEGORIES];
      if (allCategories.includes(category)) {
        return { category, desc };
      }
    }
    return { category: '', desc: description };
  };

  const form = useForm({
    resolver: zodResolver(transactionSchema),
    defaultValues: {
      type: defaultType,
      description: '',
      amount: 0,
      date: new Date().toISOString().split('T')[0],
      category: '',
    },
  });

  // Reset form when dialog opens/closes or transaction changes
  useEffect(() => {
    if (open) {
      if (transaction) {
        const { category, desc } = parseDescriptionAndCategory(transaction.description);
        form.reset({
          type: transaction.type,
          description: desc,
          amount: transaction.amount,
          date: transaction.date,
          category,
        });
      } else {
        form.reset({
          type: defaultType,
          description: '',
          amount: 0,
          date: new Date().toISOString().split('T')[0],
          category: '',
        });
      }
    }
  }, [open, transaction, defaultType, form]);

  const transactionType = form.watch('type');
  const categories = transactionType === 'income' ? INCOME_CATEGORIES : EXPENSE_CATEGORIES;

  const handleSubmit = async (data: z.infer<typeof transactionSchema>) => {
    const description = data.category 
      ? `${data.category} - ${data.description}`
      : data.description;

    await onSubmit({
      type: data.type,
      description,
      amount: data.amount,
      date: data.date,
    });
    onOpenChange(false);
  };

  // Check if transaction is linked to an order (auto-generated)
  const isAutoGenerated = transaction?.order_id != null;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[425px] max-h-[90dvh] flex flex-col overflow-hidden" onInteractOutside={(e) => e.preventDefault()}>
        <DialogHeader className="shrink-0">
          <DialogTitle className="font-display flex items-center gap-2">
            {transactionType === 'income' ? (
              <TrendingUp className="h-5 w-5 text-success" />
            ) : (
              <TrendingDown className="h-5 w-5 text-destructive" />
            )}
            {isEditing ? 'Editar Transação' : 'Nova Transação'}
          </DialogTitle>
        </DialogHeader>

        {isAutoGenerated && (
          <div className="shrink-0 bg-muted/50 border border-border rounded-md p-3 text-sm text-muted-foreground">
            Esta transação foi gerada automaticamente a partir de um pedido. 
            Alguns campos não podem ser editados.
          </div>
        )}

        <Form {...form}>
          <form onSubmit={form.handleSubmit(handleSubmit)} className="flex flex-col flex-1 min-h-0 overflow-hidden">
            <ScrollArea className="flex-1 min-h-0 pr-4">
              <div className="space-y-4">
                <FormField
                  control={form.control}
                  name="type"
              render={({ field }) => (
                <FormItem>
                  <FormLabel className="flex items-center gap-1.5">
                    <ArrowUpDown className="h-4 w-4" />
                    Tipo *
                  </FormLabel>
                  <Select 
                    onValueChange={field.onChange} 
                    value={field.value}
                    disabled={isAutoGenerated}
                  >
                    <FormControl>
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                      <SelectItem value="income">
                        <span className="flex items-center gap-2">
                          <TrendingUp className="h-4 w-4 text-success" />
                          Receita
                        </span>
                      </SelectItem>
                      <SelectItem value="expense">
                        <span className="flex items-center gap-2">
                          <TrendingDown className="h-4 w-4 text-destructive" />
                          Despesa
                        </span>
                      </SelectItem>
                    </SelectContent>
                  </Select>
                  <FormMessage />
                </FormItem>
              )}
            />

            {!isAutoGenerated && (
              <FormField
                control={form.control}
                name="category"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel className="flex items-center gap-1.5">
                      <FolderOpen className="h-4 w-4" />
                      Categoria
                    </FormLabel>
                    <Select onValueChange={field.onChange} value={field.value}>
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder="Selecione uma categoria" />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        {categories.map((cat) => (
                          <SelectItem key={cat} value={cat}>
                            {cat}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />
            )}

            <FormField
              control={form.control}
              name="description"
              render={({ field }) => (
                <FormItem>
                  <FormLabel className="flex items-center gap-1.5">
                    <FileText className="h-4 w-4" />
                    Descrição *
                  </FormLabel>
                  <FormControl>
                    <Input 
                      placeholder="Ex: Compra de chocolate belga" 
                      {...field} 
                      disabled={isAutoGenerated}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="amount"
              render={({ field }) => (
                <FormItem>
                  <FormLabel className="flex items-center gap-1.5">
                    <DollarSign className="h-4 w-4" />
                    Valor *
                  </FormLabel>
                  <FormControl>
                    <CurrencyInput
                      value={field.value}
                      onChange={field.onChange}
                      placeholder="R$ 0,00"
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

                <FormField
                  control={form.control}
                  name="date"
                  render={({ field }) => (
                    <FormItem className="overflow-hidden">
                      <FormLabel className="flex items-center gap-1.5">
                        <CalendarDays className="h-4 w-4" />
                        Data
                      </FormLabel>
                      <FormControl>
                        <Input type="date" {...field} className="max-w-full" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>
            </ScrollArea>

            <div className="flex flex-col-reverse sm:flex-row gap-3 pt-4 sm:justify-end shrink-0 border-t mt-4">
              <Button
                type="button"
                variant="outline"
                className="w-full sm:w-auto"
                onClick={() => onOpenChange(false)}
              >
                Cancelar
              </Button>
              <Button 
                type="submit" 
                variant={transactionType === 'income' ? 'default' : 'destructive'}
                className="w-full sm:w-auto"
                disabled={isLoading}
              >
                {isLoading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                {isEditing ? 'Salvar' : 'Registrar'}
              </Button>
            </div>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}
